CREATE OR REPLACE PROCEDURE END_INT (ID_INT NUMBER, DATA_EFF DATE, DUR NUMBER)
IS
DATA_PREV	DATE;
TIME_PARADOX3 	EXCEPTION;
BEGIN
	SELECT DATA_PREVISTA INTO DATA_PREV FROM INTERVENTO
	WHERE ID_INTERVENTO = ID_INT;
		
	IF (DATA_EFF < DATA_PREV) THEN
		RAISE TIME_PARADOX3;
	END IF;
	UPDATE INTERVENTO
	SET DATA_EFFETTIVA = DATA_EFF,
		DURATA_EFFETTIVA = DUR
	WHERE ID_INTERVENTO = ID_INT;

EXCEPTION
	WHEN NO_DATA_FOUND THEN
	RAISE_APPLICATION_ERROR(-20090,'Questo intervento non esiste');

	WHEN TIME_PARADOX3 THEN
	RAISE_APPLICATION_ERROR(-20091,'La data effettiva precede la data prevista');

END;
/
