CREATE OR REPLACE FUNCTION GET_INF
(DATA_INT IN DATE)
RETURN INFERMIERE.CF_INF%TYPE
IS
INF		CHAR(16);
BEGIN
--Cerca gli infermieri che non sono mai stati assegnati ad un intervento
BEGIN
SELECT MIN(CF_INF) INTO INF FROM (
	SELECT I.CF_INF, A.ID_INTERVENTO FROM
	INFERMIERE I LEFT JOIN ASSISTE A ON I.CF_INF = A.CF_INF)
	WHERE ID_INTERVENTO IS NULL;
	RETURN INF;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
	INF := NULL;
END;
--Cerca gli infermieri liberi nella data e ora inserite e che non hanno assistito
--più di due interventi in quel giorno
CASE
WHEN INF IS NULL THEN
SELECT MIN(CF_INF) INTO INF FROM (
	SELECT CF_INF, DATA_PREVISTA, COUNT(*) FROM
	ASSISTE A JOIN INTERVENTO I ON A.ID_INTERVENTO = I.ID_INTERVENTO
	WHERE I.DATA_PREVISTA <> DATA_INT
	GROUP BY CF_INF, DATA_PREVISTA
	HAVING COUNT(*) < 3);
	RETURN INF;
END CASE;
END;
/
