CREATE OR REPLACE PROCEDURE PROGRAMMAZIONE_INTERVENTO
(CF_MED IN VARCHAR, CF_PAZ IN VARCHAR, SALA_OP IN INTEGER, TIPO_INTERVENTO IN VARCHAR,
DURATA IN NUMBER, DATA_PREVISTA IN VARCHAR)
IS
DATA_PREV	DATE := to_date(DATA_PREVISTA, 'dd-mm-yyyy HH24:mi:ss');
ID_RIC		RICOVERO.ID_RICOVERO%TYPE;
COUNT_SO	INTEGER;
COUNT_MED	INTEGER;
C_DIM		INTEGER;
DATA_RIC	DATE;
CF_NEW_MED	PERSONA.CF%TYPE;
CF_NEW_INF	PERSONA.CF%TYPE;
SPEC		MEDICO.SPECIALIZZAZIONE%TYPE;
ID_INT		INTERVENTO.ID_INTERVENTO%TYPE;
IND		INTEGER;
EX1		EXCEPTION;
EX2		EXCEPTION;
EX3		EXCEPTION;
EX4		EXCEPTION;
EX5		EXCEPTION;
EX6		EXCEPTION;
BEGIN
--Medico e paziente non possono coincidere
IF(CF_PAZ = CF_MED) THEN
RAISE EX1;
END IF;
--La data dell'intervento non può essere precedente a quella del ricovero
SELECT MAX(DATA_RICOVERO) INTO DATA_RIC FROM RICOVERO R
WHERE R.CF_PAZ = CF_PAZ;
IF(DATA_PREV < DATA_RIC) THEN
RAISE EX2;
END IF;
--In una sala operatoria non possono esserci più di 3 interventi al giorno
SELECT COUNT(*) INTO COUNT_SO FROM INTERVENTO I
WHERE I.NUM_SALA_OPERA = SALA_OP
AND I.DATA_PREVISTA = DATA_PREV;
IF(COUNT_SO = 3) THEN
RAISE EX3;
END IF;
--Un medico non può essere assegnato a più di 2 interventi al giorno
COUNT_MED := COUNT_INT(CF_MED, DATA_PREV);
IF(COUNT_MED = 2) THEN
RAISE EX4;
END IF;
--Calcolo ID intervento
SELECT seq_intervento.NEXTVAL INTO ID_INT FROM DUAL;
DBMS_OUTPUT.PUT_LINE('ID INTERVENTO: ' || ID_INT);
--Calcolo ID ricovero
SELECT ID_RICOVERO INTO ID_RIC FROM RICOVERO
WHERE DATA_RICOVERO = (SELECT MAX(DATA_RICOVERO) FROM RICOVERO R
WHERE R.CF_PAZ = CF_PAZ);
--Non si può effettuare un intervento su un paziente che è stato dimesso
SELECT COUNT(*) INTO C_DIM FROM DIMISSIONE
WHERE ID_RICOVERO = ID_RIC;
IF(C_DIM <> 0) THEN
RAISE EX5;
END IF;
--Creazione dell'intervento
INSERT INTO INTERVENTO(ID_INTERVENTO, DATA_PREVISTA, DATA_EFFETTIVA, TIPO, DURATA_PREVISTA, DURATA_EFFETTIVA, NUM_SALA_OPERA, ID_RICOVERO, CF_PAZ)
VALUES (ID_INT, DATA_PREV, NULL, TIPO_INTERVENTO, DURATA, NULL, SALA_OP, ID_RIC, CF_PAZ);
--Assegnazione al medico
INSERT INTO EFFETTUA(CF_MED, ID_INTERVENTO) VALUES(CF_MED, ID_INT);
--Se la durata dell'intervento è maggiore a 6 ore si assegna un altro medico con la stessa specializzazione, se disponibile
IF(DURATA > 6) THEN
SELECT SPECIALIZZAZIONE INTO SPEC FROM MEDICO M
WHERE M.CF_MED = CF_MED;
SELECT CF_MED INTO CF_NEW_MED FROM MEDICO M
WHERE M.SPECIALIZZAZIONE = SPEC AND COUNT_INT(M.CF_MED, DATA_PREV) < 2;
INSERT INTO EFFETTUA(CF_MED, ID_INTERVENTO) VALUES(CF_NEW_MED, ID_INT);
END IF;
--Assegnazione degli infermieri in base alla durata dell'intervento:
--da 1 a 3 ore: 2 infermieri;
--da 4 a 5 ore: 3 infermieri;
--da 6 ore in su: 4 infermieri.
IF(DURATA > 0 AND DURATA < 4) THEN
IND := 2;
ELSIF(DURATA > 3 AND DURATA < 6) THEN
IND := 3;
ELSE
IND := 4;
END IF;
FOR A IN 1..IND LOOP
CF_NEW_INF := GET_INF(DATA_PREV);
DBMS_OUTPUT.PUT_LINE('CF INFERMIERE: ' || CF_NEW_INF);
INSERT INTO ASSISTE(CF_INF, ID_INTERVENTO) VALUES(CF_NEW_INF, ID_INT);
CF_NEW_INF := '';
END LOOP;
EXCEPTION
WHEN EX1 THEN
RAISE_APPLICATION_ERROR(-20050, 'MEDICO E PAZIENTE NON POSSONO COINCIDERE');
WHEN EX2 THEN
RAISE_APPLICATION_ERROR(-20051, 'LA DATA INTERVENTO RISULTA PRECEDENTE ALLA DATA DI RICOVERO');
WHEN EX3 THEN
RAISE_APPLICATION_ERROR(-20052, 'LA SALA OPERATORIA HA RAGGIUNTO IL LIMITE GIORNALIERO DI INTERVENTI NELLA DATA INSERITA');
WHEN EX4 THEN
RAISE_APPLICATION_ERROR(-20053, 'IL MEDICO HA RAGGIUNTO IL LIMITE GIORNALIERO DI INTERVENTI NELLA DATA INSERITA');
WHEN EX5 THEN
RAISE_APPLICATION_ERROR(-20055, 'IL PAZIENTE RISULTA DIMESSO');
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20054, 'NON SONO DISPONIBILI ALTRI MEDICI PER EFFETTUARE L INTERVENTO');
END;
/
