CREATE OR REPLACE PROCEDURE VIS_PAZ_STANZ_REP(NUMERO_S NUMBER,NOM_REP VARCHAR)
IS
	C1	SYS_REFCURSOR;
BEGIN
	OPEN C1 FOR
	SELECT CF_PAZ,NOME,COGNOME,(TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')) - TO_NUMBER(TO_CHAR(P.DATA_DI_NASCITA,'YYYY'))) AS ETA
 	FROM REPARTO R JOIN E_TENUTO ED ON R.NOME_REPARTO=ED.NOME_REPARTO JOIN RICOVERO RI ON ED.ID_RICOVERO=RI.ID_RICOVERO JOIN PERSONA P ON RI.CF_PAZ=P.CF
	WHERE R.NOME_REPARTO=NOM_REP AND N_STANZE=NUMERO_S;
	DBMS_SQL.RETURN_RESULT(C1);
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('Non ci sono pazienti.');
END;
--Visualizzare il CF, nome, cognome e età dei pazienti in una stanza di un reparto
/
