CREATE OR REPLACE VIEW VIS_RIC_ULTIMA_SETT
AS
	SELECT CF,NOME,COGNOME,NOME_REPARTO,DATA_RICOVERO
	FROM RICOVERO R JOIN PERSONA P ON R.CF_PAZ=P.CF JOIN E_TENUTO ET ON R.ID_RICOVERO=ET.ID_RICOVERO
	WHERE DATA_RICOVERO >= (SYSDATE-7)
/
--Visualizzare CF, NOME, COGNOME, REPARTO E DATA_RICOVERO dei pazienti per i ricoveri dell'ultima settimana