CREATE OR REPLACE PROCEDURE VIS_ANALISI_PAZ(CF_PAZx CHAR)
AS
	C1	SYS_REFCURSOR;
BEGIN
	OPEN C1 FOR
	SELECT DATA_ORA_PRELIEVO,GLUCOSIO,CLORO,POTASSIO,SODIO
	FROM ANALISI A JOIN CARTELLA_CLINICA CC ON A.CODICE_CC=CC.CODICE_CC JOIN RICOVERO R ON CC.ID_RICOVERO=R.ID_RICOVERO
	WHERE R.CF_PAZ=CF_PAZx;
	DBMS_SQL.RETURN_RESULT(C1);
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('Questo paziente non ha analisi');
END;
--Visualizzazione delle analisi di un paziente
/
