CREATE OR REPLACE VIEW VIS_FOGLI_TERAPIA
AS
	SELECT FF.CODICE_CC,FF.CF_FISIOTERAPISTA,FF.DATA_ORA,FF.DEAMBULAZIONE,FF.ELETTR_MUSC,FF.RINF_MUSC
	FROM FOGLIO_FISIOTERAPIA FF JOIN CARTELLA_CLINICA CC ON FF.CODICE_CC=CC.CODICE_CC JOIN RICOVERO R ON R.ID_RICOVERO=CC.ID_RICOVERO
	WHERE NOT EXISTS(SELECT *
			FROM DIMISSIONE D
			WHERE R.ID_RICOVERO <> D.ID_RICOVERO)
--Visualizzare i fogli fisioterapia di tutti i pazienti non ancora dimessi.
/
