CREATE OR REPLACE PROCEDURE VISUALIZZA_PAZIENTE (ID_RIC NUMBER)
IS
--cartella clinica
	CART_CLIN CHAR(10);
--intervento
	DATA_INTERVENTO	DATE;
	TIPO_INTERVENTO	VARCHAR(20);
	DURATA_INTERVENTO NUMBER;
--analisi
	CLORO_ANALISI NUMBER;
	GLUCOSIO_ANALISI NUMBER;
	POTASSIO_ANALISI NUMBER;
	SODIO_ANALISI NUMBER;
--esame
	DATA_ESAME DATE;
	TIPO_ESAME2 VARCHAR(30);
	ESITO_ESAME	NUMBER;
BEGIN
--ottengo il codice della cartella clinica
	SELECT CODICE_CC INTO CART_CLIN FROM CARTELLA_CLINICA
	WHERE ID_RICOVERO = ID_RIC;
--ottengo i dati da intervento
	SELECT DATA_EFFETTIVA, TIPO, DURATA_EFFETTIVA INTO DATA_INTERVENTO, TIPO_INTERVENTO, DURATA_INTERVENTO FROM INTERVENTO I
	WHERE ID_RIC = I.ID_RICOVERO AND DATA_PREVISTA = (SELECT MAX(DATA_PREVISTA) FROM INTERVENTO I WHERE I.ID_RICOVERO = ID_RIC);
	DBMS_OUTPUT.PUT_LINE('ULTIMO INTERVENTO EFFETTUATO: ' || DATA_INTERVENTO || ' ' || TIPO_INTERVENTO || ' ' || DURATA_INTERVENTO);
--ottengo i dati da analisi
	SELECT GLUCOSIO, CLORO, POTASSIO, SODIO INTO GLUCOSIO_ANALISI, CLORO_ANALISI, POTASSIO_ANALISI, SODIO_ANALISI FROM ANALISI
	WHERE CODICE_CC = CART_CLIN AND DATA_ORA_PRELIEVO = (SELECT MAX(DATA_ORA_PRELIEVO) FROM ANALISI A WHERE A.CODICE_CC = CART_CLIN);
	DBMS_OUTPUT.PUT_LINE('ULTIMA ANALISI EFFETTUATA:');
	DBMS_OUTPUT.PUT_LINE('GLUCOSIO: ' || GLUCOSIO_ANALISI);
	DBMS_OUTPUT.PUT_LINE('CLORO: ' || CLORO_ANALISI);
	DBMS_OUTPUT.PUT_LINE('POTASSIO: ' || POTASSIO_ANALISI);
	DBMS_OUTPUT.PUT_LINE('SODIO: ' || SODIO_ANALISI);
--ottengo i dati da esame
	SELECT DATA_ORA, TIPO_ESAME, ESITO INTO DATA_ESAME, TIPO_ESAME2, ESITO_ESAME FROM ESAMI
	WHERE CODICE_CC = CART_CLIN AND DATA_ORA = (SELECT MAX(DATA_ORA) FROM ESAMI E WHERE E.CODICE_CC = CART_CLIN);
	DBMS_OUTPUT.PUT_LINE('ULTIMO ESAME EFFETTUATO:' || DATA_ESAME || ' ' || TIPO_ESAME2 || ' ' || ESITO_ESAME);
END;
/
