create or replace trigger TR_INT
BEFORE
    INSERT ON INTERVENTO
    FOR EACH ROW
DECLARE
    DIM DIMISSIONE.ID_DIMISSIONE%TYPE;
    LAST_INT DATE;
    C NUMBER;
    EX1 EXCEPTION;
    EX2 EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO C
    FROM DIMISSIONE D
    WHERE D.ID_RICOVERO = :NEW.ID_RICOVERO;        
    IF(C <> 0) THEN
        RAISE EX1;
    END IF;

    SELECT MAX(DATA_EFFETTIVA) INTO LAST_INT
    FROM INTERVENTO I
    WHERE I.CF_PAZ = :NEW.CF_PAZ;
    IF(LAST_INT IS NOT NULL) THEN
        IF(:NEW.DATA_PREVISTA - LAST_INT < 15) THEN
            RAISE EX2;
        END IF;
    END IF;
EXCEPTION
    WHEN EX1 THEN
           RAISE_APPLICATION_ERROR(-20031, 'IL PAZIENTE PER IL RICOVERO INSERITO � STATO DIMESSO.');
    WHEN EX2 THEN
           RAISE_APPLICATION_ERROR(-20032, 'IL PAZIENTE HA GI� SUBITO UN INTERVENTO NEGLI ULTIMI 15 GIORNI');
END;
/
