CREATE OR REPLACE TRIGGER max_10_int_in_una_sett
BEFORE
	INSERT ON EFFETTUA
	FOR EACH ROW
DECLARE
	n1		NUMBER(2,0):=0;
	n2		NUMBER(2,0):=0;
	ecc_1		EXCEPTION;
	ecc_2		EXCEPTION;
BEGIN
	SELECT COUNT(DISTINCT I.ID_INTERVENTO) INTO n1
	FROM INTERVENTO I JOIN EFFETTUA E ON I.ID_INTERVENTO=E.ID_INTERVENTO
	WHERE :NEW.CF_MED=E.CF_MED AND I.DATA_PREVISTA >= (SYSDATE-7);
	SELECT COUNT(DISTINCT TIPO) INTO n2
	FROM	(SELECT TIPO
		FROM INTERVENTO I JOIN EFFETTUA E ON I.ID_INTERVENTO=E.ID_INTERVENTO
		WHERE :NEW.CF_MED=E.CF_MED AND I.DATA_PREVISTA >= (SYSDATE-7));
	IF n1 > 10 THEN
		RAISE ecc_1;
	ELSIF n2 > 3 THEN
		RAISE ecc_2;
	END IF;
EXCEPTION
	WHEN ecc_1 THEN
		RAISE_APPLICATION_ERROR(-20097,'Troppi interventi per questo medico in una settimana');
	WHEN ecc_2 THEN
		RAISE_APPLICATION_ERROR(-20096,'Troppi interventi diversi per questo medico in una settimana');
END;
--Un medico può partecipare al massimo a 10 interventi in una settimana e di al più tre tipi diversi.
/
