--Ripulitura DBMS
DROP TABLE PERSONA CASCADE CONSTRAINTS;
DROP TABLE INFERMIERE CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE FISIOTERAPISTA CASCADE CONSTRAINTS;
DROP TABLE PAZIENTE CASCADE CONSTRAINTS;
DROP TABLE ha_I CASCADE CONSTRAINTS;
DROP TABLE CARTELLA_INFERMIERISTICA CASCADE CONSTRAINTS;
DROP TABLE FOGLIO_TERAPIA CASCADE CONSTRAINTS;
DROP TABLE contiene CASCADE CONSTRAINTS;
DROP TABLE FARMACO CASCADE CONSTRAINTS;
DROP TABLE DIARIO_INFERMIERISTICO CASCADE CONSTRAINTS;
DROP TABLE sintomatologia_di CASCADE CONSTRAINTS;
DROP TABLE INTERVENTO CASCADE CONSTRAINTS;
DROP TABLE assiste CASCADE CONSTRAINTS;
DROP TABLE RICOVERO CASCADE CONSTRAINTS;
DROP TABLE REPARTO CASCADE CONSTRAINTS;
DROP TABLE e_tenuto CASCADE CONSTRAINTS;
DROP TABLE DIMISSIONE CASCADE CONSTRAINTS;
DROP TABLE effettua CASCADE CONSTRAINTS;
DROP TABLE DIETA CASCADE CONSTRAINTS;
DROP TABLE VISITA CASCADE CONSTRAINTS;
DROP TABLE ha_M CASCADE CONSTRAINTS;
DROP TABLE CARTELLA_CLINICA CASCADE CONSTRAINTS;
DROP TABLE ESAMI CASCADE CONSTRAINTS;
DROP TABLE ANALISI CASCADE CONSTRAINTS;
DROP TABLE DIARIO_CLINICO CASCADE CONSTRAINTS;
DROP TABLE sintomatologia_cc CASCADE CONSTRAINTS;
DROP TABLE FOGLIO_FISIOTERAPIA CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_INTERVENTO;
DROP SEQUENCE SEQ_RICOVERO;
DROP SEQUENCE SEQ_DIMISSIONE;

--Creazione Tabella PERSONA
CREATE TABLE PERSONA(
    CF                  CHAR(16) PRIMARY KEY,
    VIA                 VARCHAR2(30),
    CITTA               VARCHAR2(20),
    CAP                 CHAR(5),
    NOME                VARCHAR2(20) NOT NULL,
    COGNOME             VARCHAR2(20) NOT NULL,
    DATA_DI_NASCITA     DATE NOT NULL,
    CELLULARE           CHAR(10),
    SESSO               CHAR(1) NOT NULL,
    CONSTRAINT CH_SESSO CHECK (SESSO IN ('M','F'))
);

--Creazione Tabella INFERMIERE
CREATE TABLE INFERMIERE(
    CF_INF              CHAR(16) PRIMARY KEY,
    ALBO                CHAR(6) NOT NULL,
    CONSTRAINT FK_CF_INF FOREIGN KEY (CF_INF) REFERENCES PERSONA(CF) ON DELETE CASCADE
);

--Creazione Tabella MEDICO
CREATE TABLE MEDICO(
    CF_MED              CHAR(16) PRIMARY KEY,
    ALBO                CHAR(6) NOT NULL,
    SPECIALIZZAZIONE    VARCHAR2(30) DEFAULT 'Medico Generale' NOT NULL,
    CONSTRAINT FK_CF_MED FOREIGN KEY (CF_MED) REFERENCES PERSONA(CF) ON DELETE CASCADE,
    CONSTRAINT CH_SPECIALIZZAZIONE CHECK (SPECIALIZZAZIONE IN ('Medicina Interna', 'Cardiologia', 'Cardiochirurgia', 'Chirurgia Generale', 'Neurochirurgia', 'Neurologia', 'Geriatria', 'Fisiatria', 'Dietologia', 'Ortopedia e traumatologia'))
);

--Creazione Tabella FISIOTERAPISTA
CREATE TABLE FISIOTERAPISTA(
    CF_FISIO            CHAR(16) PRIMARY KEY,
    ALBO                CHAR(6) NOT NULL,
    CONSTRAINT FK_CF_FISIO FOREIGN KEY (CF_FISIO) REFERENCES PERSONA(CF) ON DELETE CASCADE
);

--Creazione Tabella PAZIENTE
CREATE TABLE PAZIENTE(
    CF_PAZ              CHAR(16) PRIMARY KEY,
    CELL_FAMILIARE      CHAR(10),
    CONSTRAINT FK_CF_PAZ FOREIGN KEY (CF_PAZ) REFERENCES PERSONA(CF) ON DELETE CASCADE
);

--Creazione Tabella RICOVERO
CREATE TABLE RICOVERO(
    ID_RICOVERO         NUMBER PRIMARY KEY,
    CODICE_DIAGNOSI     NUMBER NOT NULL,
    DATA_RICOVERO       DATE NOT NULL,
    CF_PAZ              CHAR(16),
    CONSTRAINT FK_R FOREIGN KEY (CF_PAZ) REFERENCES PAZIENTE(CF_PAZ) ON DELETE CASCADE,
    --CODICE_DIAGNOSI: da 101 a 110
    CONSTRAINT CH_CODICE_DIAGNOSI CHECK (CODICE_DIAGNOSI IN (101,102,103,104,105,106,107,108,109,110))
);
CREATE SEQUENCE seq_ricovero
	MINVALUE 1000000001
	START WITH 1000000001
	INCREMENT BY 1
	CACHE 20;

--Creazione Tabella CARTELLA_INFERMIERISTICA
CREATE TABLE CARTELLA_INFERMIERISTICA(
    COD_CART_INF        CHAR(10) PRIMARY KEY,
    ID_RICOVERO         NUMBER NOT NULL,
    CONSTRAINT FK_ID_RICOVERO FOREIGN KEY (ID_RICOVERO) REFERENCES RICOVERO(ID_RICOVERO) ON DELETE CASCADE
);

--Creazione Tabella (associazione) ha_I
CREATE TABLE ha_I(
    COD_CART_INF        CHAR(10),
    CF_INF              CHAR(16),
    CONSTRAINT PK_ha PRIMARY KEY (COD_CART_INF, CF_INF),
    CONSTRAINT FK_ha_CF_INF FOREIGN KEY (CF_INF) REFERENCES INFERMIERE(CF_INF) ON DELETE CASCADE,
    CONSTRAINT FK_ha_COD_CART_INF FOREIGN KEY (COD_CART_INF) REFERENCES CARTELLA_INFERMIERISTICA(COD_CART_INF) ON DELETE CASCADE
);

--Creazione Tabella FOGLIO_TERAPIA
CREATE TABLE FOGLIO_TERAPIA(
    DATA_ORA            DATE,
    METODO_SOMMINISTRA  VARCHAR2(20) NOT NULL,
    COD_CART_INF        CHAR(10) NOT NULL,
    CONSTRAINT PK_FT PRIMARY KEY (DATA_ORA, COD_CART_INF),
    CONSTRAINT CH_METODO_SOMMINISTRA CHECK (METODO_SOMMINISTRA IN ('Orale','Rettale','Endovena','Inalatoria','Transcutanea','Intravascolare','Intramuscolare')),
    CONSTRAINT FK_COD_CART_INF FOREIGN KEY (COD_CART_INF) REFERENCES CARTELLA_INFERMIERISTICA(COD_CART_INF) ON DELETE CASCADE
);

--Creazione Tabella FARMACO
CREATE TABLE FARMACO(
    COD_FARMACO         CHAR(10) PRIMARY KEY,
    TIPO                VARCHAR2(20),
    NOME_FARMACO        VARCHAR2(20) NOT NULL,
    ASSUNZ_GIORNALIERA  NUMBER NOT NULL,
    CONSTRAINT CH_TIPO CHECK (TIPO IN ('Antimicrobico', 'Catartico', 'Emetocatartico', 'Oressizzante', 'Stomachico'))
);

--Creazione Tabella (associazione) contiene
CREATE TABLE contiene(
    DATA_ORA            DATE,
    COD_CART_INF        CHAR(10),
    COD_FARMACO         CHAR(10) NOT NULL,
    CONSTRAINT PL_contiene PRIMARY KEY (DATA_ORA, COD_CART_INF),
    CONSTRAINT FK_contiene_COD_FARMACO FOREIGN KEY (COD_FARMACO) REFERENCES FARMACO(COD_FARMACO),
    CONSTRAINT FK_contiene_DATA_ORA FOREIGN KEY (DATA_ORA, COD_CART_INF) REFERENCES FOGLIO_TERAPIA(DATA_ORA, COD_CART_INF) ON DELETE CASCADE
);

--Creazione Tabella DIARO_INFERMIERISTICO
CREATE TABLE DIARIO_INFERMIERISTICO(
    DATA_ORA            DATE,
    COD_CART_INF        CHAR(10),
    CONSTRAINT PK_DI PRIMARY KEY (DATA_ORA, COD_CART_INF),
    CONSTRAINT FK_DI FOREIGN KEY (COD_CART_INF) REFERENCES CARTELLA_INFERMIERISTICA(COD_CART_INF) ON DELETE CASCADE
);

--Creazione Tabella (attributo multivalore) sintomatologia
CREATE TABLE sintomatologia_di(
    DATA_ORA            DATE,
    SINTOMO             VARCHAR2(30) NOT NULL,
    COD_CART_INF        CHAR(10),
    CONSTRAINT PK_SINT PRIMARY KEY (DATA_ORA, COD_CART_INF),
    CONSTRAINT FK_SINT FOREIGN KEY (DATA_ORA, COD_CART_INF) REFERENCES DIARIO_INFERMIERISTICO(DATA_ORA, COD_CART_INF) ON DELETE CASCADE,
    CONSTRAINT CH_SINTOMAT CHECK (SINTOMO IN ('Gonfiore', 'Febbre', 'Tosse', 'Vomito', 'Diarrea', 'Infiammazione', 'Dolori addominali', 'Nausea', 'Stanchezza', 'Stitichezza'))
);

--Creazione Tabella INTERVENTO
CREATE TABLE INTERVENTO(
    ID_INTERVENTO       NUMBER PRIMARY KEY,
    DATA_PREVISTA       DATE NOT NULL,
    DATA_EFFETTIVA      DATE,
    TIPO                VARCHAR2(20) NOT NULL,
    DURATA_PREVISTA     NUMBER NOT NULL,
    DURATA_EFFETTIVA    NUMBER,
    NUM_SALA_OPERA      NUMBER NOT NULL,
    ID_RICOVERO         NUMBER,
    CF_PAZ              CHAR(16),
    CONSTRAINT FK_INT_ID FOREIGN KEY (ID_RICOVERO) REFERENCES RICOVERO(ID_RICOVERO) ON DELETE CASCADE,
    CONSTRAINT FK_INT_CF FOREIGN KEY (CF_PAZ) REFERENCES PAZIENTE(CF_PAZ) ON DELETE CASCADE,
    CONSTRAINT CH_NUM_SALA_OPERA CHECK (NUM_SALA_OPERA IN (10,11,12,13,14,15)),
    CONSTRAINT CH_TIPO_INT CHECK (TIPO IN ('Amputazione', 'Anastomosi', 'Artrodesi', 'Artroplastica', 'Aspirazione', 'Asportazione', 'Cardioplegia', 'Cardiotomia', 'Cateterismo', 'Cistectomia', 'Drenaggio', 'Gastrotomia'))
);
CREATE SEQUENCE seq_intervento
	MINVALUE 3000000001
	START WITH 3000000001
	INCREMENT BY 1
	CACHE 20;

--Creazione Tabella (associazione) assiste
CREATE TABLE assiste(
    CF_INF              CHAR(16),
    ID_INTERVENTO       NUMBER,
    CONSTRAINT PK_ASSISTE PRIMARY KEY(CF_INF, ID_INTERVENTO),
    CONSTRAINT FK_A_ID FOREIGN KEY (ID_INTERVENTO) REFERENCES INTERVENTO(ID_INTERVENTO) ON DELETE CASCADE,
    CONSTRAINT FK_A_CF FOREIGN KEY (CF_INF) REFERENCES INFERMIERE(CF_INF) ON DELETE CASCADE
);

--Creazione Tabella REPARTO
CREATE TABLE REPARTO(
    N_PIANO             NUMBER NOT NULL,
    NOME_REPARTO        VARCHAR2(40) NOT NULL,
    N_POSTI             NUMBER DEFAULT 5 NOT NULL,
    N_STANZE            NUMBER DEFAULT 15 NOT NULL,
    CONSTRAINT PK_REP PRIMARY KEY (N_PIANO, NOME_REPARTO),
    CONSTRAINT CH_N_PIANO CHECK (N_PIANO IN (0,1,2,3,4,5)),
    CONSTRAINT CH_N_POSTI CHECK (N_POSTI IN (1,2,3,4,5,6)),
    CONSTRAINT CH_NOME_REPARTO CHECK (NOME_REPARTO IN ('Cardiologia', 'Anatomia e Istologia patologica', 'Anestesia e Rianimazione', 'Chirurgia', 'Oncologia', 'Gastroenterologia', 'Medicina Generale', 'Ortopedia e Traumatologia', 'Radiologia','Diabetologia','Geriatria','Medicina Interna','Neurologia','Pediatria','Urologia','Psichiatria'))
);

--Creazione Tabella (associazione) è tenuto
CREATE TABLE e_tenuto(
    ID_RICOVERO         NUMBER PRIMARY KEY,
    DATA_ORA            DATE NOT NULL,
    N_PIANO             NUMBER NOT NULL,
    NOME_REPARTO        VARCHAR2(40),
    CONSTRAINT FK_ID_ET FOREIGN KEY (ID_RICOVERO) REFERENCES RICOVERO(ID_RICOVERO) ON DELETE CASCADE,
    CONSTRAINT FK_N_PIANO FOREIGN KEY (N_PIANO, NOME_REPARTO) REFERENCES REPARTO(N_PIANO, NOME_REPARTO) ON DELETE CASCADE
);

--Creazione Tabella DIMISSIONE
CREATE TABLE DIMISSIONE(
    ID_DIMISSIONE       NUMBER PRIMARY KEY,
    DATA_ORA            DATE NOT NULL,
    CODICE_DIAGNOSI     NUMBER DEFAULT 100 NOT NULL,
    MOD_DIMISSIONE      NUMBER NOT NULL,
    ID_RICOVERO         NUMBER,
    CONSTRAINT FK_ID_DIM FOREIGN KEY (ID_RICOVERO) REFERENCES RICOVERO(ID_RICOVERO) ON DELETE CASCADE,
    --da 0 (completamente autonomo) a 10 (completamente dipendente)
    CONSTRAINT CH_MOD_DIMISSIONE CHECK (MOD_DIMISSIONE IN (0,1,2,3,4,5,6,7,8,9,10)),
    --CODICE_DIAGNOSI: da 100 a 110 (dove 100 indica completamente guarito)
    CONSTRAINT CH_CODICE_DIM CHECK (CODICE_DIAGNOSI IN (100,101,102,103,104,105,106,107,108,109,110))
);
CREATE SEQUENCE seq_dimissione
	MINVALUE 5000000001
	START WITH 5000000001
	INCREMENT BY 1
	CACHE 20;

--Creazione Tabella (associazione) effettua
CREATE TABLE effettua(
    CF_MED              CHAR(16),
    ID_INTERVENTO       NUMBER,
    CONSTRAINT PK_EFFETTUA PRIMARY KEY(CF_MED, ID_INTERVENTO),
    CONSTRAINT FK_EFF FOREIGN KEY (CF_MED) REFERENCES MEDICO(CF_MED) ON DELETE CASCADE,
    CONSTRAINT FK_ID_EFF FOREIGN KEY (ID_INTERVENTO) REFERENCES INTERVENTO(ID_INTERVENTO) ON DELETE CASCADE
);

--Creazione Tabella DIETA
CREATE TABLE DIETA(
    CODICE_DIETA        CHAR(10) PRIMARY KEY,
    TIPO                VARCHAR2(30) NOT NULL,
    KCAL                NUMBER NOT NULL,
    PROTEINE            NUMBER NOT NULL,
    GRASSI              NUMBER NOT NULL,
    CF_MED              CHAR(16),
    ID_RICOVERO         NUMBER,
    CONSTRAINT FK_CF_MED_DIETA FOREIGN KEY (CF_MED) REFERENCES MEDICO(CF_MED) ON DELETE CASCADE,
    CONSTRAINT FK_ID_RICOVERO_DIETA FOREIGN KEY (ID_RICOVERO) REFERENCES RICOVERO(ID_RICOVERO) ON DELETE CASCADE,
    CONSTRAINT CH_TIPO_DIETA CHECK (TIPO IN ('Normoenergetica', 'Lattea integrata', 'Liquida', 'Semiliquida', 'Ipocalorica', 'Ipoglicidica IDDM', 'Ipoglicidica NIDDM', 'Lipolipidica', 'Ipoproteica', 'Ipopurinica', 'Ipernutritiva', 'Astringente'))
);

--Creazione Tabella VISITA
CREATE TABLE VISITA(
    DATA_ORA_PREVISTA   DATE PRIMARY KEY,
    DATA_ORA_EFFETTIVA  DATE,
    TIPO_VISITA         VARCHAR2(20) DEFAULT 'Generica' NOT NULL,
    CF_PAZ              CHAR(16),
    CF_MED              CHAR(16),
    ID_RICOVERO         NUMBER,
    CONSTRAINT FK_CF_PAZ_V FOREIGN KEY (CF_PAZ) REFERENCES PAZIENTE(CF_PAZ) ON DELETE CASCADE,
    CONSTRAINT FK_CF_MED_V FOREIGN KEY (CF_MED) REFERENCES MEDICO(CF_MED) ON DELETE CASCADE,
    CONSTRAINT FK_ID_RICOVERO_V FOREIGN KEY (ID_RICOVERO) REFERENCES RICOVERO(ID_RICOVERO) ON DELETE CASCADE,
    CONSTRAINT CH_TIPO_VISITA CHECK (TIPO_VISITA IN ('Cardiologica', 'Dietologica', 'Fisiatrica', 'Geriatrica', 'Neurologica', 'Generica'))
);

--Creazione Tabella CARTELLA_CLINICA
CREATE TABLE CARTELLA_CLINICA(
    CODICE_CC           CHAR(10) PRIMARY KEY,
    SINTOMO             VARCHAR2(30) NOT NULL,
    ID_RICOVERO         NUMBER,
    CONSTRAINT FK_ID_RICOVERO_C FOREIGN KEY (ID_RICOVERO) REFERENCES RICOVERO(ID_RICOVERO) ON DELETE CASCADE,
    CONSTRAINT CH_SINTOMO_CC CHECK (SINTOMO IN ('Gonfiore', 'Febbre', 'Tosse', 'Vomito', 'Diarrea', 'Infiammazione', 'Dolori addominali', 'Nausea', 'Stanchezza', 'Stitichezza'))
);

--Creazione Tabella (associazione) ha_M
CREATE TABLE ha_M(
    CODICE_CC           CHAR(10) PRIMARY KEY,
    CF_MED              CHAR(16),
    CONSTRAINT FK_CODICE_CC_H FOREIGN KEY (CODICE_CC) REFERENCES CARTELLA_CLINICA(CODICE_CC) ON DELETE CASCADE,
    CONSTRAINT FK_CF_MED_H FOREIGN KEY (CF_MED) REFERENCES MEDICO(CF_MED) ON DELETE CASCADE
);

--Creazione Tabella ESAMI
CREATE TABLE ESAMI(
    DATA_ORA            DATE,
    TIPO_ESAME          VARCHAR2(30) NOT NULL,
    ESITO               NUMBER NOT NULL,
    CODICE_CC           CHAR(10),
    CONSTRAINT PK_ES PRIMARY KEY (DATA_ORA, CODICE_CC),
    CONSTRAINT FK_CODICE_CC_ES FOREIGN KEY (CODICE_CC) REFERENCES CARTELLA_CLINICA(CODICE_CC) ON DELETE CASCADE,
    --Esito -> 0 Positivo, 1 Negativo
    CONSTRAINT CH_ESITO CHECK (ESITO IN (0, 1)),
    CONSTRAINT CH_TIPO_ESAME CHECK (TIPO_ESAME IN ('Radiografia', 'Risonanza Magnetica', 'TAC', 'Ecografia', 'PET'))
);

--Creazione Tabella ANALISI
CREATE TABLE ANALISI(
    DATA_ORA_PRELIEVO   DATE PRIMARY KEY,
    GLUCOSIO            NUMBER NOT NULL,
    CLORO               NUMBER NOT NULL,
    POTASSIO            NUMBER NOT NULL,
    SODIO               NUMBER NOT NULL,
    CODICE_CC           CHAR(10),
    CONSTRAINT FK_CODICE_CC_AN FOREIGN KEY (CODICE_CC) REFERENCES CARTELLA_CLINICA(CODICE_CC) ON DELETE CASCADE
);

--Creazione Tabella DIARIO_CLINICO
CREATE TABLE DIARIO_CLINICO(
    DATA_ORA			DATE,
    CODICE_CC			CHAR(10),
    CONSTRAINT PK_DC PRIMARY KEY (DATA_ORA, CODICE_CC),
    CONSTRAINT FK_DC FOREIGN KEY (CODICE_CC) REFERENCES CARTELLA_CLINICA(CODICE_CC) ON DELETE CASCADE
);

CREATE TABLE FOGLIO_FISIOTERAPIA(
    DATA_ORA			DATE,
    RINF_MUSC			NUMBER,
    ELETTR_MUSC			NUMBER,
    DEAMBULAZIONE		NUMBER,
    CF_FISIOTERAPISTA	CHAR(16),
    CODICE_CC			CHAR(10),
    CONSTRAINT PK_FF PRIMARY KEY (DATA_ORA, CF_FISIOTERAPISTA, CODICE_CC),
    CONSTRAINT FK_FF1 FOREIGN KEY (CF_FISIOTERAPISTA) REFERENCES FISIOTERAPISTA(CF_FISIO) ON DELETE CASCADE,
    CONSTRAINT FK_FF2 FOREIGN KEY (CODICE_CC) REFERENCES CARTELLA_CLINICA(CODICE_CC) ON DELETE CASCADE,
    --Livello di autonomia del paziente. Da 0 (insufficiente o non collaborativo) a 10 (autonomo o collaborativo)
	CONSTRAINT CH_RINF_MUSC CHECK (RINF_MUSC IN (0,1,2,3,4,5,6,7,8,9,10)),
    CONSTRAINT CH_ELETTR_MUSC CHECK (ELETTR_MUSC IN (0,1,2,3,4,5,6,7,8,9,10)),
    CONSTRAINT CH_DEAMBULAZIONE CHECK (DEAMBULAZIONE IN (0,1,2,3,4,5,6,7,8,9,10))
);

--Creazione Tabella sintomatologia_cc
CREATE TABLE sintomatologia_cc(
    DATA_ORA			DATE,
    SINTOMO				VARCHAR2(30) NOT NULL,
    CODICE_CC			CHAR(10),
    CONSTRAINT PK_SINT_CC PRIMARY KEY(DATA_ORA, CODICE_CC),
    CONSTRAINT FK_SINT_CC FOREIGN KEY(DATA_ORA, CODICE_CC) REFERENCES DIARIO_CLINICO(DATA_ORA, CODICE_CC) ON DELETE CASCADE,
    CONSTRAINT CH_SINTOMAT_CC CHECK (SINTOMO IN ('Gonfiore', 'Febbre', 'Tosse', 'Vomito', 'Diarrea', 'Infiammazione', 'Dolori addominali', 'Nausea', 'Stanchezza', 'Stitichezza'))
);
