--DROP
DROP USER DB_ADMIN CASCADE;
DROP USER MEDICO CASCADE;
DROP USER INFERMIERE CASCADE;
DROP USER FISIOTERAPISTA CASCADE;
DROP USER PAZIENTE CASCADE;

DROP ROLE MED_ROLE;
DROP ROLE INF_ROLE;
DROP ROLE FISIO_ROLE;
DROP ROLE PAZ_ROLE;

--Utente amministratore
CREATE USER DB_ADMIN IDENTIFIED BY admin;
GRANT ALL PRIVILEGES TO DB_ADMIN;

--Utenti
CREATE USER MEDICO IDENTIFIED BY medico;
CREATE USER INFERMIERE IDENTIFIED BY infermiere;
CREATE USER FISIOTERAPISTA IDENTIFIED BY fisioterapista;
CREATE USER PAZIENTE IDENTIFIED BY paziente;

--Creazione dei ruoli
CREATE ROLE MED_ROLE;
CREATE ROLE INF_ROLE;
CREATE ROLE FISIO_ROLE;
CREATE ROLE PAZ_ROLE;

GRANT MED_ROLE TO MEDICO;
GRANT PAZ_ROLE TO MEDICO;

GRANT INF_ROLE TO INFERMIERE;
GRANT PAZ_ROLE TO INFERMIERE;

GRANT FISIO_ROLE TO FISIOTERAPISTA;
GRANT PAZ_ROLE TO FISIOTERAPISTA;

GRANT PAZ_ROLE TO PAZIENTE;
