GRANT CONNECT, CREATE SESSION TO INF_ROLE;

--INF_ROLE
GRANT SELECT,INSERT ON ha_I TO INF_ROLE;
GRANT SELECT,INSERT ON CARTELLA_INFERMIERISTICA TO INF_ROLE;

GRANT SELECT,INSERT,DELETE ON FOGLIO_TERAPIA TO INF_ROLE;

GRANT SELECT,INSERT,DELETE,UPDATE ON DIARIO_INFERMIERISTICO TO INF_ROLE;
GRANT SELECT,INSERT,DELETE,UPDATE ON sintomatologia_di TO INF_ROLE;

GRANT SELECT ON contiene TO INF_ROLE;
GRANT SELECT ON FARMACO TO INF_ROLE;
GRANT SELECT ON INTERVENTO TO INF_ROLE;
GRANT SELECT ON assiste TO INF_ROLE;
GRANT SELECT ON RICOVERO TO INF_ROLE;
GRANT SELECT ON REPARTO TO INF_ROLE;
GRANT SELECT ON e_tenuto TO INF_ROLE;
GRANT SELECT ON DIMISSIONE TO INF_ROLE;
GRANT SELECT ON effettua TO INF_ROLE;
GRANT SELECT ON DIETA TO INF_ROLE;
GRANT SELECT ON VISITA TO INF_ROLE;
GRANT SELECT ON CARTELLA_CLINICA TO INF_ROLE;
GRANT SELECT ON ESAMI TO INF_ROLE;
GRANT SELECT ON ANALISI TO INF_ROLE;
GRANT SELECT ON DIARIO_CLINICO TO INF_ROLE;
GRANT SELECT ON sintomatologia_cc TO INF_ROLE;
GRANT SELECT ON FOGLIO_FISIOTERAPIA TO INF_ROLE;


GRANT EXECUTE ON VISUALIZZA_PAZIENTE TO INF_ROLE;
GRANT EXECUTE ON VIS_PAZ_STANZ_REP TO INF_ROLE;
GRANT EXECUTE ON VIS_FOGLIO_FISIO_E_ESAMI_PAZ TO INF_ROLE;
GRANT EXECUTE ON NUM_INT_EFF_PAZ TO INF_ROLE;
GRANT EXECUTE ON CF_PAZ_DA_NOME TO INF_ROLE;
