GRANT CONNECT, CREATE SESSION TO MED_ROLE;

--MED_ROLE
GRANT SELECT,INSERT,UPDATE ON cartella_clinica TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE ON ricovero TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE ON ha_M TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE ON e_tenuto TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE ON dimissione TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE ON diario_clinico TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE ON sintomatologia_cc TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE ON intervento TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE ON foglio_terapia TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE ON contiene TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE ON farmaco TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE ON effettua TO MED_ROLE;

GRANT SELECT,INSERT,UPDATE,DELETE ON visita TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON dieta TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON esami TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON analisi TO MED_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON assiste TO MED_ROLE;

GRANT SELECT ON foglio_fisioterapia TO MED_ROLE;
GRANT SELECT ON reparto TO MED_ROLE;
GRANT SELECT ON cartella_infermieristica TO MED_ROLE;
GRANT SELECT ON diario_infermieristico TO MED_ROLE;
GRANT SELECT ON sintomatologia_di TO MED_ROLE;

GRANT EXECUTE ON PROGRAMMAZIONE_INTERVENTO TO MED_ROLE;
GRANT EXECUTE ON PRENOTA_VISITA TO MED_ROLE;
GRANT EXECUTE ON VISUALIZZA_PAZIENTE TO MED_ROLE;
GRANT EXECUTE ON VIS_PAZ_STANZ_REP TO MED_ROLE;
GRANT EXECUTE ON VIS_FOGLIO_FISIO_E_ESAMI_PAZ TO MED_ROLE;
GRANT EXECUTE ON TRY_DIM TO MED_ROLE;
GRANT EXECUTE ON PROG_INT_ANALISI TO MED_ROLE;
GRANT EXECUTE ON INTERVENTI_DA_FARE TO MED_ROLE;
GRANT EXECUTE ON END_INT TO MED_ROLE;
GRANT EXECUTE ON NUM_INT_EFF_PAZ TO MED_ROLE;
GRANT EXECUTE ON CF_PAZ_DA_NOME TO MED_ROLE;
