GRANT CONNECT, CREATE SESSION TO FISIO_ROLE;

--FISIO_ROLE
GRANT SELECT ON ha_I TO FISIO_ROLE;
GRANT SELECT ON CARTELLA_INFERMIERISTICA TO FISIO_ROLE;
GRANT SELECT ON FOGLIO_TERAPIA TO FISIO_ROLE;
GRANT SELECT ON contiene TO FISIO_ROLE;
GRANT SELECT ON FARMACO TO FISIO_ROLE;
GRANT SELECT ON DIARIO_INFERMIERISTICO TO FISIO_ROLE;
GRANT SELECT ON sintomatologia_di TO FISIO_ROLE;
GRANT SELECT ON INTERVENTO TO FISIO_ROLE;
GRANT SELECT ON assiste TO FISIO_ROLE;
GRANT SELECT ON RICOVERO TO FISIO_ROLE;
GRANT SELECT ON REPARTO TO FISIO_ROLE;
GRANT SELECT ON e_tenuto TO FISIO_ROLE;
GRANT SELECT ON DIMISSIONE TO FISIO_ROLE;
GRANT SELECT ON effettua TO FISIO_ROLE;
GRANT SELECT ON DIETA TO FISIO_ROLE;
GRANT SELECT ON VISITA TO FISIO_ROLE;
GRANT SELECT ON ha_M TO FISIO_ROLE;
GRANT SELECT ON ESAMI TO FISIO_ROLE;
GRANT SELECT ON ANALISI TO FISIO_ROLE;
GRANT SELECT ON DIARIO_CLINICO TO FISIO_ROLE;
GRANT SELECT ON sintomatologia_cc TO FISIO_ROLE;

GRANT SELECT,INSERT ON CARTELLA_CLINICA TO FISIO_ROLE;
GRANT SELECT,INSERT,UPDATE ON FOGLIO_FISIOTERAPIA TO FISIO_ROLE;

GRANT EXECUTE ON VISUALIZZA_PAZIENTE TO FISIO_ROLE;
GRANT EXECUTE ON VIS_PAZ_STANZ_REP TO FISIO_ROLE;
GRANT EXECUTE ON VIS_FOGLIO_FISIO_E_ESAMI_PAZ TO FISIO_ROLE;
GRANT EXECUTE ON NUM_INT_EFF_PAZ TO FISIO_ROLE;
GRANT EXECUTE ON CF_PAZ_DA_NOME TO FISIO_ROLE;
